[project]
name = "amortsched"
version = "0.1.0"
description = "Amortization Schedule Generator"
readme = "README.md"
authors = [{ name = "Gledi Caushaj", email = "gledi.alb@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "starlette",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "rodi",
    "orjson",
    "mashumaro[orjson]",
    "rich",
    "click",
]

[project.optional-dependencies]
prod = ["uvicorn[standard]"]

[dependency-groups]
tests = [
    "pytest",
    "coverage",
    "pytest-asyncio",
    "factory-boy",
    "pytest-factoryboy",
]
dev = ["debugpy", "ipython", "ruff"]

[project.scripts]
amortsched = "amortsched.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "B", "I"]
ignore = []
