[project]
name = "amortsched"
version = "0.1.0"
description = "Amortization Schedule Generator"
readme = "README.md"
authors = [{ name = "Gledi Caushaj", email = "gledi.alb@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["flask>=3.1.2", "rich>=14.2.0"]

[project.scripts]
amortsched = "amortsched.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["ipython>=9.8.0", "ruff>=0.14.8"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "B", "I"]
ignore = []
